name: walkntalk
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^3.4.1
  firebase_auth: ^5.2.1
  firebase_cloud_firestore:
  firebase_storage:
  google_sign_in: ^6.2.1
  firebase_app_check: ^0.3.2
  sign_in_with_apple: ^4.1.0
  cloud_firestore: ^5.6.1
  image_picker: ^1.1.2
  provider: ^6.1.2
  shared_preferences: any
  cached_network_image: ^3.4.1
  flutter_image_compress: ^2.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
